services:
  frontend:
    restart: always
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4173:4173"
    env_file:
      - ./frontend/.env
  backend:
    restart: always
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
  nginx:
    depends_on:
      - frontend
      - backend
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etx/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  postgres:
    image: postgres:16.4-alpine
    restart: always
    container_name: postgres
    ports:
      - 5431:5432
    volumes:
      - ~/postgres/budget_buddy/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
