services:
  frontend:
    restart: always
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "4173:4173"
    env_file:
      - ./frontend/.env
  backend:
    restart: always
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
