services:
  frontend:
    restart: always
    build:
      context: ./frontend
    container_name: budget-buddy-frontend
    ports:
      - "4173:4173"
    env_file:
      - ./frontend/.env
    networks:
      - nginx_default
  backend:
    restart: always
    build:
      context: ./backend
    container_name: budget-buddy-backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true
