root = "."
tmp_dir = "bin"

[build]
  bin = "./bin/main"
  cmd = "go build -o ./bin/main ."
  delay = 20
  exclude_dir = ["bin", "vendor", "database"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = [] 
  include_ext = ["go"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
